name: CI Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubunti-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100' 

      - name: Nerdbank
        uses: aarnott/nbgv@master

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test
  
